# Generated by Django 5.1.4 on 2024-12-17 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('epoca_siembra_sugerida', models.CharField(max_length=100)),
                ('densidad_siembra', models.CharField(max_length=100)),
                ('ciclo_floracion', models.CharField(max_length=100)),
                ('habito', models.CharField(max_length=100)),
                ('usos_sugeridos', models.TextField()),
                ('caracteristicas_productivas', models.TextField()),
                ('evaluacion_nacional_inase_inia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50, unique=True)),
                ('departamento_origen', models.CharField(max_length=100)),
                ('pureza', models.DecimalField(decimal_places=2, max_digits=5)),
                ('germinacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso_mil_semillas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enlace_analisis', models.URLField(blank=True, null=True)),
                ('codigo_qr', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('cultivar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='api.cultivar')),
            ],
        ),
    ]
